{
 "title": "Folding@home",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(fah_up, instance)" }
  ]
 },
 "panels": [
  {
   "title": "Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fah_slot_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Percent Done",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum without (queue) (fah_percent_done{instance=\"$instance\"})",
     "legendFormat": "Slot {{slot}}"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fah_eta{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Frames",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "fah_frames_done{instance=\"$instance\"}"
    },
    {
     "expr": "fah_total_frames{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Idle Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fah_idle{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Points Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (queue) (fah_ppd{instance=\"$instance\"})",
     "legendFormat": "Slot {{slot}}"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "fah_description{instance=\"$instance\"}"
    },
    {
     "expr": "fah_idle{instance=\"$instance\"}"
    },
    {
     "expr": "fah_paused{instance=\"$instance\"}"
    },
    {
     "expr": "fah_state{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "fah_reason{instance=\"$instance\"}"
    },
    {
     "expr": "fah_queue_error{instance=\"$instance\"}"
    }
   ]
  }
 ]
}