{
 "title": "MPH",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(mph_up, instance)" } },
   {
    "name": "coin",
    "label": "Coin",
    "query": "label_values(mph_hashrate{instance=\"$instance\"}, coin)"
   }
  ]
 },
 "panels": [
  {
   "title": "24 Hour Earnings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mph_recent_credits{instance=\"$instance\", coin=\"$coin\"}",
     "legendFormat": "{{coin}}"
    },
    {
     "expr": "mph_recent_credits{instance=\"$instance\", coin=\"$coin\"} * ignoring(id,currency) mph_price{instance=\"$instance\", coin=\"$coin\"} + on(coin) group_left(currency) (0*mph_price{instance=\"$instance\", coin=\"$coin\"})",
     "legendFormat": "Fiat ({{currency}})"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mph_balance_confirmed{instance=\"$instance\", coin=\"$coin\"} + mph_balance_unconfirmed{instance=\"$instance\", coin=\"$coin\"}",
     "legendFormat": "{{coin}}"
    },
    {
     "expr": "(mph_balance_confirmed{instance=\"$instance\", coin=\"$coin\"} + mph_balance_unconfirmed{instance=\"$instance\", coin=\"$coin\"}) * ignoring(id,currency) mph_price{instance=\"$instance\", coin=\"$coin\"} + on(coin) group_left(currency) (0*mph_price{instance=\"$instance\", coin=\"$coin\"})",
     "legendFormat": "Fiat ({{currency}})"
    }
   ]
  },
  {
   "title": "$coin Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mph_price{instance=\"$instance\", coin=\"$coin\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "expr": "mph_raw_personal_hashrate{instance=\"$instance\", coin=\"$coin\"}",
     "legendFormat": "{{coin}} current"
    },
    {
     "expr": "avg_over_time(mph_raw_personal_hashrate{instance=\"$instance\", coin=\"$coin\"}[8h])",
     "legendFormat": "{{coin}} 8hr avg "
    }
   ]
  },
  {
   "title": "Network & Pool Hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "expr": "mph_raw_network_hashrate{instance=\"$instance\", coin=\"$coin\"}",
     "legendFormat": "{{coin}} network"
    },
    {
     "expr": "mph_raw_pool_hashrate{instance=\"$instance\", coin=\"$coin\"}",
     "legendFormat": "{{coin}} pool"
    }
   ]
  }
 ]
}