{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nvidia_info, instance)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_utilization_gpu{instance=\"$instance\"}) / sum(nvidia_device_count{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_utilization_memory{instance=\"$instance\"}) / sum(nvidia_device_count{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_gpu{instance=\"$instance\"}",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization_memory{instance=\"$instance\"}",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Power Limit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "mwatt",
   "valueName": "current",
   "targets": [
    {
     "expr": "nvidia_power_limit{instance=\"$instance\"}",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Driver",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_driver_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_temperatures{instance=\"$instance\"}",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "nvidia_power_usage{instance=\"$instance\"} / 1e3",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Graphics Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_clock_current_graphics{instance=\"$instance\"} * 1e6",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "nvidia_clock_appdefault_graphics{instance=\"$instance\"} * 1e6",
     "legendFormat": "gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Total Encoder/Decoder Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(nvidia_utilization_process_decutil{instance=\"$instance\"}) by (minor)",
     "legendFormat": "gpu{{minor}} - Decode"
    },
    {
     "expr": "sum(nvidia_utilization_process_encutil{instance=\"$instance\"}) by (minor)",
     "legendFormat": "gpu{{minor}} - Encode"
    }
   ]
  },
  {
   "title": "Process SM Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  nvidia_utilization_process_smutil{instance=\"$instance\"}\n)\n   + on(pid) group_left(name)\n(\n   0 * nvidia_utilization_process_name{instance=\"$instance\"}\n)",
     "legendFormat": "gpu{{minor}} - {{name}} [{{pid}}]"
    }
   ]
  },
  {
   "title": "PCIe TX/RX Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_pcie_tx_bytes{instance=\"$instance\"}",
     "legendFormat": "TX-gpu{{minor}}"
    },
    {
     "expr": "nvidia_pcie_rx_bytes{instance=\"$instance\"}",
     "legendFormat": "RX-gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_fanspeed{instance=\"$instance\"}",
     "legendFormat": "{{kubernetes_pod_node_name}}"
    }
   ]
  }
 ]
}