{
 "title": "Quadro",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "query_result(aquaero_up)" },
   {
    "name": "instance",
    "query": "query_result(aquaero_up{job=\"$job\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "aquaero_temp{job=\"$job\", instance=\"$instance\", id=\"sensor1\"}",
     "legendFormat": "Intake"
    },
    {
     "expr": "aquaero_temp{job=\"$job\", instance=\"$instance\", id=\"sensor2\"}",
     "legendFormat": "PSU"
    },
    {
     "expr": "aquaero_temp{job=\"$job\", instance=\"$instance\", id=\"sensor3\"}",
     "legendFormat": "VRM"
    },
    {
     "expr": "aquaero_temp{job=\"$job\", instance=\"$instance\", id=\"sensor4\"}",
     "legendFormat": "Ambient"
    }
   ]
  },
  {
   "title": "All Temperatures",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "aquaero_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "All Fans",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "RPM" }
   ],
   "targets": [
    {
     "expr": "aquaero_rpm{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}