{
 "title": "Windows Host",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(wmi_os_time, job)" },
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values(wmi_os_time{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_os_time{instance=~\"$host\"} - wmi_system_system_up_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_threads{instance=~\"$host\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"$host\",mode=\"idle\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (wmi_os_physical_memory_free_bytes{instance=~\"$host\"} / wmi_cs_physical_memory_bytes{instance=~\"$host\"}) > 0"
    }
   ]
  },
  {
   "title": "Network RX/TX (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sum(increase(wmi_net_bytes_received_total{instance=~\"$host\"}[24h]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(increase(wmi_net_bytes_sent_total{instance=~\"$host\"}[24h]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sort_desc(wmi_logical_disk_free_bytes{instance=~\"$host\",volume=~\"(^[A-Z]:$)\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(wmi_cpu_time_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU load per process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "CPU load" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (rate(wmi_process_cpu_time_total{instance=~\"$host\", process !~\"Idle\"}[5m]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "wmi_memory_available_bytes{instance=~\"$host\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "wmi_memory_pool_paged_bytes{instance=~\"$host\"}",
     "legendFormat": "Paged"
    },
    {
     "expr": "wmi_memory_committed_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Average commit bytes per process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (process) (wmi_process_private_bytes{instance=~\"$host\", process=~\".*\"})",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_net_bytes_received_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m])",
     "legendFormat": "RX"
    },
    {
     "expr": "irate(wmi_net_bytes_sent_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wmi_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Network discarded/error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "repeat": "host",
   "yaxes": [
    { "format": "pps", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_net_packets_outbound_discarded{instance=~\"$host\",nic!~\"isatap.+\"}[5m]) + irate(wmi_net_packets_outbound_errors{instance=~\"$host\"}[5m])",
     "legendFormat": "TX"
    },
    {
     "expr": "irate(wmi_net_packets_received_discarded{instance=~\"$host\", nic!~\"isatap.+\"}[5m]) + irate(wmi_net_packets_received_errors{instance=~\"$host\"}[5m])",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m])",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(wmi_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m])",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  {
   "title": "Number of disk page reads/writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wmi_memory_swap_page_reads_total{instance=~\"$host\"}[1m])",
     "legendFormat": "Swap Read"
    },
    {
     "expr": "rate(wmi_memory_swap_page_writes_total{instance=~\"$host\"}[1m])",
     "legendFormat": "Swap Write"
    }
   ]
  }
 ]
}